version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
    networks:
      - s5wesley
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
    networks:
      - s5wesley
    restart: always

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - "5000:80"
    environment:
      REDIS_HOST: redis
    deploy:
      replicas: 1
    networks:
      - s5wesley
    restart: always

  worker:
    image: dockersamples/examplevotingapp_worker
    ports:
      - "80:80"
    deploy:
      replicas: 1
    networks:
      - s5wesley
    restart: always

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - "5001:80"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    deploy:
      replicas: 1
    networks:
      - s5wesley
    restart: always

volumes:
  redis-data:
  db-data:

networks:
  s5wesley:
